[server]
  http_port = 8080
[net]
  full_node = "https://api.trongrid.io"
  slack_webhook = "...(your slack webhook url)"
[log]
  log_path = "logs"
  log_file = "app.log"
  log_level = "INFO"
[database]
  host = "127.0.0.1:3306"
  db = "tron_tracker"
  user = "root"
  password = ""
  start_date = "231102"
  start_num = 56084338
  valid_tokens = [
    ["TUPM7K8REVzD2UdV4R5fe5M8XbnR2DdoJ6", "HTX"],
    ["TKfjV9RNKJJCqPvBtK8L7Knykh7DNWvnYt", "WBTT"],
    ["TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9", "BTC"],
    ["TXpw8XeWYeTUd4quDskoUqeQPowRh4jY65", "WBTC"],
    ["TRFe3hT5oYhjSZ6f3ji5FJ7YCfrkWnHRvh", "ETH"],
    ["THb4CqiFdwNHsWsQCs4JhzwjMWys4aqCbF", "ETHOLD"],
    ["TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t", "USDT"],
    ["TPYmHEhy5n8TCEfYGqW2rPxsghSfzghPDn", "USDDOLD"],
    ["TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8", "USDC"],
    ["TLa2f6VPqDgRE67v1736s7bJ8Ray5wYjU7", "WIN"],
    ["TMwFHYXLJaRUPeW6421aqXL4ZEzPRFGkGT", "USDJ"],
    ["TUpMhErZL2fhh4sVNULAbNKLokS4GjC1F4", "TUSD"],
    ["TCFLL5dx5ZJdKnWuesXxi1VPwjLVmWZZy9", "JST"],
    ["TSSMHYeV2uE9qYH95DqyoCuNCzEL1NvU3S", "SUN"],
    ["TKkeiboTkxXKJpbmVFbv4a8ov5rAfRDMf9", "SUNOLD"],
    ["TFczxzPhnThNSqr5by8tvxsdCFRRz6cPNq", "NFT"],
    ["TDyvndWuvX5xTBwHPYJi7J3Yq8pq8yh62h", "HT"],
    ["THbVQp8kMjStKNnf2iCY6NEzThKMK5aBHg", "DOGE"],
    ["TAFjULxiVgT4qWk6UZwjqwZXTSaGaqnVp4", "BTT"],
    ["TMz2SWatiAtZVVcH2ebpsbVtYwUPT9EdjH", "BUSD"],
    ["TU3kjFuhtEo42tsCBtfYUAZxoqQ4yuSLQ5", "sTRX"],
    ["TNUC9Qb1rRpS5CbWLmNMxXBjyFoydXjWFR", "WTRX"],
    ["TThzxNRLrW2Brp9DcTQU8i4Wd9udCWEdZ3", "stUSDT"],
    ["TGkxzkDKyMeq2T7edKnyjZoFypyzjkkssq", "wstUSDT"],
    ["TXL6rJbvmjD46zeN1JssfgxvSo99qC8MRT", "SUNDOG"],
    ["TXDk8mbtRbXeYuMNS83CfKPaYYT8XWv9Hz", "USDD"],
    ["TR3DLthpnDdCGabhVDbD3VMsiJoCXY3bZd", "LTC"],
    ["TXWkP3jLBqRGojUih1ShzNyDaN5Csnebok", "WETH"],
  ]
[defi]
  sunswap_v1 = [
    "TA3ws2ibLbWDTgCRPkBD6E3XHSPVox2Fca",
    "TA4nZoYX9vT1VdvuRPAsyFCFfvgHESfftA",
    "TAb9VFD6Qs4ZPRiNdmfft3uq8JeA6XcouZ",
    "TAk2x449m9MBmdjJRwpJU8n2XeZ8pYLS16",
    "TAnNronN8C3W7ePNcJozjyLwiVsmRkNroT",
    "TAo39Hb2k7Di6tPcUAGgnugWuyS2ERCkDs",
    "TAQHtyaFeQHqLNd6sNsq1JzXcDrURseyk6",
    "TAvzGq83QggAJJ69hYpHTZHvzaaeY3iRLV",
    "TB6FkNHxr7PAQFWoXSX82arC5wUEP3GqtB",
    "TBrEh1WHPDoMxgjbR1CfqmeNbK3eEWrSjM",
    "TBzpwaRzfs8z5UG3xP6Kw9hQek2wDufD17",
    "TC2MxAczjCkeT6AA37T96ji9yQYCafJhE1",
    "TCkBkQBnSmsNXJvdn5ihPKUjUSHrjfT5xv",
    "TCKdqmfYuf4n5cGLtzDPbSZVge7K4tjFis",
    "TCRjXHk5ny1NfyicmjHmCr4ssk1NjDUCqf",
    "TCt8v3uCnNNzhnAeyADnRw8A8hNRvxXf4K",
    "TD1Hxp9CHoSUZQ2GuBDCqhJcLZarMMPGiY",
    "TD8sUrenpwUvjohu5K8bYeT4CdJLFc58ez",
    "TDkupjr15jjB8RxFW3g5EmqmdpAs2xXK1U",
    "TDoyeqW4wkR6mJ4EbXCmtg6hfc2puzYWrS",
    "TDQaYrhQynYV9aXTYj63nwLAafRffWSEj6",
    "TEc39rJSy3LZZhrsWDUYZXJu2VuayJT5RU",
    "TEcSFn6agWjztFgxYkuD8JbVz7xMiEgDDP",
    "TEPY36EqhuKecbFheYuaMxBzLTZqXMjXsQ",
    "TEXzC4uN65PoXX7VqTMYHJm7dAzY4XnBu2",
    "TFgZc4YPhj9wQJWiDhzay5sZko5FP36eNE",
    "TFi3v5PtYRnVdC43qSvPR3upZhgreiURga",
    "TGDRfKeE3xfbYDZvg7XH36NWhUm98wfq5s",
    "TGF2JwGHjq2N1LKSPKxdWGWjdwFgXjiWGZ",
    "TGf5wvfkK3rF2AJViTPjczpXKnESKNqzRU",
    "TGRaDWm5vFqrYjLuDdfS5Cjz9h8oZ73Dzx",
    "TGwZiWGmYiFk6HPqA3aXjM9QkYWpM1ePkX",
    "TH2mEwTKNgtg8psR6Qx2RBUXZ48Lon1ygu",
    "THK84crFZcX59u2nKjXTRhT9Yg4Hp4DjZz",
    "THKvB1b142fYJZiyf8FbykiJYkfoW6tTpj",
    "THmn5Sv1DqAPLrr5v2kRJysEvm5236HXCy",
    "THobnrUEFCnT1B2dsWSq3pzXF578fU9Dp1",
    "THrXVbFuaGyro1bPq8oxh6Ey2UpL1cYiB2",
    "TJ3mvzmKS8tXMTYmpyN8XnWP8h99y3f412",
    "TJ7XfVPyYLHhmNpW2jmLXMca4gSkK1qNea",
    "TJmTeYk5zmg8pNPGYbDb2psadwVLYDDYDr",
    "TJWAi1BPukJeZ6xcJ2RUuhQPJstKzGt4Zn",
    "TK26GYHcu6tD7Y2MMxjYTqAQ5MMLjjM8NP",
    "TKAtLoCB529zusLfLVkGvLNis6okwjB7jf",
    "TKG8HDAJVq6AAcp6NX69KbvNzZhVfuBzzG",
    "TKjcUGWAMXCtp8acJn2Zvqatbg1tcxygV5",
    "TKJYoAbbLMsZkC7bonqiyzNmqtGu1iD7in",
    "TKKJqcQnEEzMRmbvDGR6R8p1e9eAaJ4y74",
    "TLaeHRNDoP2YaccQwqzYJdJjwfzJ6DcKR5",
    "TLLBBiX3HqVZZsUQTBXgurA3pdw317PmjM",
    "TLXmsR5dut3Kdxzqbe57URReETC72TtDBh",
    "TM65QN3qb6we58PzvMUcfjNKjHeVDPR7nM",
    "TM8WFPUimbkZuTfV7SL1ZQ9JFUoYPotViW",
    "TMfyHvqiUVT67K3A5duRwGyaquGkDWo8Wg",
    "TMsXsgjhLJbKnw5rVovXKNCyjeHFsMoDTD",
    "TMYitD3dRxjCQV86zAvXtqjct5AtJFcHpL",
    "TN1aaewZ68VAFjZJDfzkFfivGPcgojzvHw",
    "TN9HnZxxkcC3GpwPM92FWQkPEyxD42gvYC",
    "TNCrFKFsuQKD3KC5fq8FZzv3THtqu7PFjA",
    "TNd7EghMXSEoptqfn6doCYtPXDFuLeDFcJ",
    "TNusWhjNbSzL3FmXySfW1tnGFJsxWAr5gY",
    "TPavNqt8xhoBp4NNBSdEx3FBP24NBfVRxU",
    "TPt4RPxqXFWZkVNxNSvFxoDy7g3nP342kh",
    "TQcia2H2TU3WrFk9sKtdK9qCfkW8XirfPQ",
    "TQHtYhVXkUfB58vuK97eeejR6LJgpBSSSh",
    "TQi2ggLmUHUyd4H1qy8hcptXXdLmeRyBTr",
    "TQn9Y2khEsLJW1ChVWFMSMeRDow5KcbLSE",
    "TQnkxvgfeJPA1SdBAfk4oDT31go7cQJ86T",
    "TRjAiDf6VC5Qte2LtAQxBFtszy9LKxUzM4",
    "TS8MDSj4FCnpnPB6bAqVUQiMVzGPcobqe9",
    "TSC1cM82VCPGxs2hCuXCpoKmDpLJbHwMK3",
    "TSJWbBJAS8HgQCMJfY5drVwYDa7JBAm6Es",
    "TSvTGZb5wfWbYeMXfLX3vD45EaqvtnYJpv",
    "TT5B32NmL6znPfpoD31MtfJAL9QKtv7dfK",
    "TTeye8CZKNRmQNFeAGgC7g9pfvqZ5tjhVD",
    "TTGci6Be9Ynf42xtidzbFq85Dqva3xny7z",
    "TThQqQjsWvhRNhgHR7MaH8fy7j9njuzQUR",
    "TTqn2K7TvEff54r2NQJcL54iAHbjsW1iMe",
    "TTRHt9YkWokzNJqRX6cceqdH5hhcivMbZr",
    "TTuexAJ37d8z7Ur1vaYbpiNxnzZNRNVH3V",
    "TUEYcyPAqc4hTg1fSuBCPc18vGWcJDECVw",
    "TUjUzpE7aK1xx9LqHGyJvk1mFEAV8J2SAj",
    "TUWNGupDCWN2muGxnAM7tTndbkT9tCmwun",
    "TVaRhuyWr37F9yW4YSZvry86J39pPZ6vVE",
    "TVdGvChxgWLY5TPE6Zbo2r6gKJn7mYkQB7",
    "TVrZ3PjjFGbnp44p6SGASAKrJWAUjCHmCA",
    "TW2v5MU3njqu8d6EWHvpEuUDzdCg1ZAAwu",
    "TW6e3j5e97zbGRrbfHrsrZ1df4NZg4rK2g",
    "TWMJyK5JNVJvZnxQNKWSqnSUzMTaYjU5cs",
    "TWpeen3D9JK3kviHEZ61cgJcZAHvmWNivi",
    "TWqpMi6TMrCqLuaSmb8X9XJD3kmbAfurTb",
    "TWUj7Ax2NCpXWCGp4Yhd5WzpgLZARxakdC",
    "TXCMEAn1dfzjqRaDkLPSsmcAhMFCFukhdW",
    "TXTRBwNfyKVjh9ybk8McVvsW3njfKgJfoj",
    "TXVCiU1XvGvUrQPiuwVzFCXefs6w14vZcS",
    "TXX1i3BWKBuTxUmTERCztGyxSSpRagEcjX",
    "TXxdEAhy39GJb9aqZw9Ju8QBxGxasLPh38",
    "TY69bLD2CWAHGTWKokr1hwWcVJLF9j6g45",
    "TYN6Wh11maRfzgG7n5B6nM5VW1jfGs9chu",
    "TYukBQZ2XXCcRCReAUguyXncCWNY9CEiDQ",
  ]

  sunswap_v2 = [
    "TKzxdSv2FZKQrEqkKVgp5DcwEXBEKMg2Ax"
  ]

  sunswap_v3 = [
    "TFVisXFaijZfeyeSjCEVkHfex7HGdTxzF9",
    "TJ4NNy8xZEqsowCBhLvZ45LCqPdGjkET5j",
    "TSUUVjysXV8YqHytSNjfkNXnnB49QDvZpx",
  ]

  sunpump = [
    "TG9nDZMUtC4LBmrWSdNXNi8xrKzXTMMSKT",
    "TQHj5QZA8PaHBcAGkYdi8QxdtuNabuVx5r",
    "TTfvyrAz86hbZk5iDpKD78pqLGgi8C7AAw",
    "TZFs5ch1R1C4mmjwrrmZqeqbUgGpxY1yWB",
    "TSiiYf1b1PV1fpT9T7V4wy11btsNVajw1g",
    "TRs4TG1vizrtkVXAM1CsuWvxtXat3J7nTu",
  ]

  justlend = [
    "TGjYzgCyPobsNS9n6WcbdLVR9dH7mWqFx7", # Unitroller
    "TE2RzoSV3wFK99w6J9UnnZ4vLfXYoxvRwP",
    "TXJgMdjVX5dKiQaUi9QobwNxtSQaFqccvd",
    "TL5x9MtSnDy537FXKx53yAaHRRNdg9TkkA",
    "TGBr8uh9jBVHJhhkwSJvQN2ZAKzVkxDmno",
    "TRg6MnpsFXc82ymUPgf5qbj59ibxiEDWvv",
    "TLeEu311Cbw63BcmMHDgDLu7fnk9fqGcqT",
    "TWQhCXaWz4eHK4Kd1ErSDHjMFPoPc9czts",
    "TUY54PVeH6WCcYCd6ZXXoBDsHytN9V5PXt",
    "TR7BUFRQeq1w5jAZf1FKx85SHuX6PfMqsV",
    "TSXv71Fy5XdL3Rh2QfBoUu3NAaM4sMif8R",
    "TFpPyDCKvNFgos3g3WVsAqMrdqhB81JXHE",
    "TPXDpkg9e3eZzxqxAUyke9S4z4pGJBJw9e",
    "TNSBA6KvSvMoTqQcEgpVK7VhHT3z7wifxy",
    "TUaUHU9Dy8x5yNi1pKnFYqHWojot61Jfto",
    "TX7kybeP6UwTBRHLNPYmswFESHfyjm9bAS",
    "TLHASseQymmpGQdfAyNjkMXFTJh8nzR2x2",
    "TJQ9rbVe9ei3nNtyGgBL22Fuu2xYjZaLAQ",
    "TWBxQMb6RD3qmkXUXpNwVCYbL8SHNreru6",
    "TD5SdLw5scR6mXgyMK2xKrFJpauDjpKqrW",
    "TKFRELGGoRgiayhwJTNNLqCNjFoLBh3Mnf",
    "TD8bq1aFY8yc9nsD2rfqqJGDtkh7aPpEpr", # PriceOracle
  ]

  bttc = [
    "TB183GXRHjhd6gN81tRgkhxxVKVZqV2iE6",
    "TBSEHyzxKkM2MCvcKKpcEGgz5fFC2BD17Z",
    "TCNZa3n91ES8wB2cpd7SQdWTX51kcVnZ8f",
    "TCRaHnktKiSL8wMAeL5FE6XVMr115dQD5g",
    "TCtZg6ELHBZb1FzntFw6WP1aotvq5px1Nn",
    "TDgrSuii9e7HLfY1DhEBxkcFa3vrLgS3Gx",
    "TDpYFyUVzVt3qk9BW1obyABtCn4vAMwoQ7",
    "TEHTjbuQfiJsTb2UdKHjMgmFGwLDqVDNh5",
    "TEpjT8xbAe3FPCPFziqFfEjLVXaw9NbGXj",
    "TERZyb9z3RW23HzkSuSsN34wgyJp1vQxta",
    "TFPG3Jw9xywpyTApKBoJSnAE8RtUNTP3sY",
    "TFVDNebNYWcgabUTtULiWXK3oJPDuagL4t",
    "TFyrjevd44V81Fgn57sDPaF1fp3WaiRudc",
    "TGruPDjZARYo6FYm7gLTExuJZgdjDzJAmc",
    "TH6JAd7DNka8Q6oKqkQMWJ6TYdLG6fQ6Kv",
    "THCjSfRtw9ddHcrsy38JNp5o6JNgxmMhnn",
    "THHbapLdbXv6dpzYouTTAwN8bxt8ffYAHK",
    "TJ62dk6vScEeJN3no5XqGsTx6tqaCHasCR",
    "TJVjaUrn6PNpCDYLvdRTXmwBULND2a9AkS",
    "TJZQLJLnk6o1e8N9ipsaY8fFvhEHQhmKSR",
    "TKtiDkzuCCxD5xe3zeo6dhn2qmkdgPezzC",
    "TKvGr1u1nihZu2xhzxTJeX2UFYA6kAK3pg",
    "TLFnvxqowWEwin8myL65rPeuBnsixzcyPM",
    "TLQQdzeQbdhS8apa1Vpmwn7EBNj1QovXXK",
    "TLZHieP2s7T87NB7T7zpzoNU4goCgKN5yd",
    "TMvs6n9qy1R13CPd1AfxhW41GBG21NSXNj",
    "TN5iTE6yjoiDsWPi1NzULbrdaQmMChVFaT",
    "TNeu6uHcYxZR8rx6b44NMxDbeVhAuvfmaV",
    "TPjgpfHASHLnzkJv9eyYzdxSRVj9dvDgFv",
    "TPkYpqBAdSqaRs2cuhcWG6bNnF7x1HGNUz",
    "TPQsNDfD7cCiShb3oH4gcPQdYDomggFAoJ",
    "TQ1cN2SPyuoGP52XeaZ77gDv3SE4r6g4eu",
    "TREF4V5EkQjZ9Lu3zhxpKFvDFghigCCVKT",
    "TRyQMRRoYhVfEbi4CLAMDWA76ae3djHoKj",
    "TSWWLv8iysnmpwVeMxmimqfB2Ni2rueieD",
    "TTuZ9aoUgK8KD1hQQzppfwjci7nx6pkWv4",
    "TU1CmpmWbCrFXqLLqMaKL2Q1d34bJNYLJe",
    "TUyomXRswgWAX867h9GWeBezKW3SJd5mVP",
    "TVbnfYUp8uEt42qhRdcLsaPJHd1NFHfyUJ",
    "TWis8P9dhB7UGfsZtW2qjR3XiYFMSejT1Y",
    "TWmSodQ4JfNwH2qDdfK8mhkrAfuawLk56v",
    "TWpm2TREcdKVER2SZz1jAQjihL2aCMFtU2",
    "TX8uhjDfHP4anSJuAn197xJTPguKJWGDUH",
    "TXJQSbh9KitfCRTjH8ua9cuAXPNcA2uzvK",
    "TXxcmgoYpfNLfn5N11gSb6H7hEQC2BqSNt",
    "TZ1ggYx3CQzp3dKAKQk1n8Lht9TR2Fguy2",
  ]

  usdtcasino = [
    'TU4vEruvZwLLkSfV9bNw12EJTPvNr7Pvaa'
  ]
